[project]
name = "epub-to-mdbook"
version = "0.1.0"
description = "A simple tool to convert ePub files as mdBooks for Web-friendly reading"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ebooklib-md>=0.22",
    "markdownify>=0.14.1",
    "beautifulsoup4>=4.13.3",
]
